name: Deploy KikEventAdmin to VPS

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build -- --configuration production

    # Cette étape nous confirmera l'emplacement exact en cas d'erreur
    - name: Check build output
      run: find dist -maxdepth 4

    - name: Deploy to VPS via SCP
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        # On utilise une étoile simple pour capturer tout le contenu du build
        source: "dist/**/*"
        target: "/var/www/kikevent-admin"
        # On utilise 3 pour retirer 'dist/nom-du-projet' et laisser le contenu de 'browser'
        # Si 'browser' apparaît encore sur le VPS, on passera à 4 au prochain coup.
        strip_components: 3